use crate::schema::{invites, ntfy_users, uptime_states, users};
use rand::{Rng, distributions::Alphanumeric};
use rocket::serde::{Deserialize, Serialize};
use rocket_db_pools::diesel::prelude::*;
use std::time::SystemTime;
use uuid::Uuid;

pub type ID = Uuid;

/// Ntfy.sh instance 'managed' user for whoever is using the service,
/// which is created with read-only permissions for their own topic.
/// A lot of this information is provided to the user and can be reset
/// by the user at any point (not for 'tier' or 'permission' obviously).
#[derive(Debug, Clone, Serialize, Queryable, Selectable, Insertable)]
#[diesel(table_name = ntfy_users)]
#[serde(crate = "rocket::serde")]
pub struct NtfyUser {
    pub id: ID,
    pub enabled: bool,
    pub topic: String,
    #[serde(rename(serialize = "permission"))]
    pub topic_permission: String,
    pub username: String,
    pub password: String,
    pub tier: String,
}

#[derive(Debug, Copy, Clone, Eq, PartialEq, Deserialize, Serialize, diesel_derive_enum::DbEnum)]
#[ExistingTypePath = "crate::schema::sql_types::UserTypeEnum"]
#[serde(crate = "rocket::serde")]
pub enum UserType {
    Normal,
    Admin,
}

#[derive(Debug, Clone, Serialize, Queryable, Selectable, Insertable)]
#[diesel(table_name = users)]
#[serde(crate = "rocket::serde")]
pub struct User {
    pub id: ID,
    pub user_type: UserType,
    pub created_at: SystemTime,
    pub invites_limit: i64,
    pub invites_used: i64,
    pub access_token: String,
    pub up_delay: i16,
    pub ntfy_id: ID,
    pub language_code: String,
    pub maint_window_start_utc: Option<i16>,
    pub maint_window_end_utc: Option<i16>,
}

impl User {
    pub fn new(user_type: UserType, invites_limit: i64, up_delay: Option<u16>, language_code: String, ntfy: &NtfyUser) -> User {
        let rng = rand::thread_rng();
        let secret_part: String = rng.sample_iter(&Alphanumeric).take(16).map(char::from).collect();
        User {
            id: Uuid::new_v4(),
            user_type,
            created_at: SystemTime::now(),
            invites_limit,
            invites_used: 0,
            access_token: format!("tk_{secret_part}"),
            up_delay: up_delay.unwrap_or(60) as i16,
            ntfy_id: ntfy.id,
            language_code,
            maint_window_start_utc: None,
            maint_window_end_utc: None,
        }
    }

    /// Check if the current UTC time-of-day falls within the maintenance window.
    /// Handles midnight-spanning windows (e.g., 23:50-00:10).
    pub fn is_in_maintenance_window(&self, now_utc_minutes: i32) -> bool {
        match (self.maint_window_start_utc, self.maint_window_end_utc) {
            (Some(start), Some(end)) => {
                let (s, e, n) = (start as i32, end as i32, now_utc_minutes);
                if s < e { n >= s && n < e } else { n >= s || n < e }
            }
            _ => false,
        }
    }
}

// @NOTE: This is the the second out of 2 diesel enum packages that I've tried,
//  and the first one is even more broken. This one works as long as you go into
//  the src/schema.rs file and remove autogenerated trair 'Clone' from there. I
//  found some conversation and question about this being asked, but they both
//  were marked as "resolved" so I'm not sure if I'm doing something wrong, or
//  if this issue will come back in the future after every migration run. Here
//  are the links:
//    - https://github.com/adwhit/diesel-derive-enum/issues/91
//    - https://github.com/adwhit/diesel-derive-enum/issues/10
//  This was written at 4:44 am and I refuse to spent any more time on fixing
//  this hack. I do not understand why the fu*ck is this feature not in diesel
//  standard library.                                       - andrew, Nov 2 2024
#[derive(Debug, Copy, Clone, Eq, PartialEq, diesel_derive_enum::DbEnum)]
#[ExistingTypePath = "crate::schema::sql_types::StatusEnum"]
pub enum UpStatus {
    Uninitialized,
    Up,
    Down,
    Paused,
}

// @NOTE: Prometheus metric encoding for oubot_uptime_state gauge.
impl From<&UpStatus> for i64 {
    fn from(s: &UpStatus) -> i64 {
        match s {
            UpStatus::Uninitialized => 0,
            UpStatus::Up => 1,
            UpStatus::Down => 2,
            UpStatus::Paused => 3,
        }
    }
}

#[derive(Debug, Clone, Queryable, Selectable, Insertable)]
#[diesel(table_name = uptime_states)]
pub struct UptimeState {
    pub id: ID,
    pub created_at: SystemTime,
    pub touched_at: SystemTime,
    pub status: UpStatus,
    pub user_id: Option<ID>,
    pub state_changed_at: SystemTime,
    pub pre_pause_status: Option<UpStatus>,
}

/// Result of a touch() call indicating what state transition occurred.
pub enum TouchResult {
    /// No state change (device was already Up or Paused)
    NoChange,
    /// Device connected for the first time (Uninitialized → Up)
    Connected,
    /// Device reconnected after being down (Down → Up), with time spent down
    Restored(std::time::Duration),
}

impl UptimeState {
    pub fn new(user_id: ID) -> UptimeState {
        let now = SystemTime::now();
        UptimeState {
            id: Uuid::new_v4(),
            created_at: now,
            touched_at: now,
            status: UpStatus::Uninitialized,
            user_id: Some(user_id),
            state_changed_at: now,
            pre_pause_status: None,
        }
    }

    /// Called when device pings. Returns the state transition that occurred.
    pub fn touch(&mut self) -> TouchResult {
        let now = SystemTime::now();
        self.touched_at = now;

        if self.status == UpStatus::Uninitialized {
            self.status = UpStatus::Up;
            self.state_changed_at = now;
            return TouchResult::Connected;
        }

        if self.status == UpStatus::Down {
            // Calculate how long power was off (since last state change to Down)
            let duration = now.duration_since(self.state_changed_at).unwrap_or_default();
            self.status = UpStatus::Up;
            self.state_changed_at = now;
            return TouchResult::Restored(duration);
        }
        TouchResult::NoChange
    }

    /// Called when timeout expires. Returns Some(duration) if state changed from Up to Down,
    /// where duration is the time power was on.
    pub fn go_down(&mut self) -> Option<std::time::Duration> {
        if self.status == UpStatus::Up {
            let now = SystemTime::now();
            // Calculate how long power was on (since last state change to Up)
            let duration = now.duration_since(self.state_changed_at).ok();
            self.status = UpStatus::Down;
            self.state_changed_at = now;
            return duration;
        }
        None
    }

    /// Pause monitoring. Only allowed from Up or Down.
    pub fn pause(&mut self) -> Result<(), &'static str> {
        match self.status {
            UpStatus::Up | UpStatus::Down => {
                self.pre_pause_status = Some(self.status);
                self.status = UpStatus::Paused;
                Ok(())
            }
            UpStatus::Paused => Err("Already paused"),
            UpStatus::Uninitialized => Err("Device not yet connected"),
        }
    }

    /// Resume monitoring. Restores pre-pause status, refreshes touched_at.
    pub fn unpause(&mut self) -> Result<(), &'static str> {
        if self.status != UpStatus::Paused {
            return Err("Not paused");
        }
        let now = SystemTime::now();
        self.status = self.pre_pause_status.unwrap_or(UpStatus::Up);
        self.pre_pause_status = None;
        self.touched_at = now;
        self.state_changed_at = now;
        Ok(())
    }
}

#[derive(Debug, Clone, Serialize)]
#[serde(crate = "rocket::serde")]
pub struct UserState {
    pub user: User,
    pub ntfy: NtfyUser,
    #[serde(skip_serializing)]
    pub uptime: UptimeState,
}

#[derive(Debug, Clone, Serialize, Queryable, Selectable, Insertable)]
#[diesel(table_name = invites)]
#[serde(crate = "rocket::serde")]
pub struct Invite {
    pub id: ID,
    pub created_at: SystemTime,
    pub token: String,
    pub is_used: bool,
    pub owner_id: Option<ID>,
    pub user_id: Option<ID>,
}

impl Invite {
    pub fn new(owner_id: ID) -> Invite {
        let rng = rand::thread_rng();
        Invite {
            id: Uuid::new_v4(),
            created_at: SystemTime::now(),
            token: rng.sample_iter(&Alphanumeric).take(24).map(char::from).collect(),
            is_used: false,
            owner_id: Some(owner_id),
            user_id: None,
        }
    }
}
