use crate::schema::{invites, ntfy_users, uptime_states, users};
use rand::{Rng, distributions::Alphanumeric};
use rocket::serde::{Deserialize, Serialize};
use rocket_db_pools::diesel::AsyncPgConnection;
use rocket_db_pools::diesel::prelude::*;
use rocket_db_pools::diesel::scoped_futures::ScopedFutureExt;
use std::time::SystemTime;
use uuid::Uuid;

pub type ID = Uuid;
type R<T> = std::result::Result<T, Box<dyn std::error::Error>>;

#[derive(Debug)]
enum CustomError {
    DieselError(diesel::result::Error),
    CreationFailed,
}

impl From<diesel::result::Error> for CustomError {
    fn from(e: diesel::result::Error) -> Self {
        CustomError::DieselError(e)
    }
}

/// Ntfy.sh instance 'managed' user for whoever is using the service,
/// which is created with read-only permissions for their own topic.
/// A lot of this information is provided to the user and can be reset
/// by the user at any point (not for 'tier' or 'permission' obviously).
#[derive(Debug, Clone, Serialize, Queryable, Selectable, Insertable)]
#[diesel(table_name = ntfy_users)]
#[serde(crate = "rocket::serde")]
pub struct NtfyUser {
    pub id: ID,
    pub enabled: bool,
    pub topic: String,
    #[serde(rename(serialize = "permission"))]
    pub topic_permission: String,
    pub username: String,
    pub password: String,
    pub tier: String,
}

#[derive(Debug, Copy, Clone, Eq, PartialEq, Deserialize, Serialize, diesel_derive_enum::DbEnum)]
#[ExistingTypePath = "crate::schema::sql_types::UserTypeEnum"]
#[serde(crate = "rocket::serde")]
pub enum UserType {
    Normal,
    Admin,
}

#[derive(Debug, Clone, Serialize, Queryable, Selectable, Insertable)]
#[diesel(table_name = users)]
#[serde(crate = "rocket::serde")]
pub struct User {
    pub id: ID,
    pub user_type: UserType,
    pub created_at: SystemTime,
    pub invites_limit: i64,
    pub invites_used: i64,
    pub access_token: String,
    pub up_delay: i16,
    pub ntfy_id: ID,
    pub language_code: String,
}

impl User {
    pub fn new(
        user_type: UserType,
        invites_limit: i64,
        up_delay: Option<u16>,
        language_code: String,
        ntfy: &NtfyUser,
    ) -> User {
        let rng = rand::thread_rng();
        let secret_part: String = rng.sample_iter(&Alphanumeric).take(32).map(char::from).collect();
        User {
            id: Uuid::new_v4(),
            user_type,
            created_at: SystemTime::now(),
            invites_limit,
            invites_used: 0,
            access_token: format!("tk_{secret_part}"),
            up_delay: up_delay.unwrap_or(30) as i16,
            ntfy_id: ntfy.id,
            language_code,
        }
    }
}

// @NOTE: This is the the second out of 2 diesel enum packages that I've tried,
//  and the first one is even more broken. This one works as long as you go into
//  the src/schema.rs file and remove autogenerated trair 'Clone' from there. I
//  found some conversation and question about this being asked, but they both
//  were marked as "resolved" so I'm not sure if I'm doing something wrong, or
//  if this issue will come back in the future after every migration run. Here
//  are the links:
//    - https://github.com/adwhit/diesel-derive-enum/issues/91
//    - https://github.com/adwhit/diesel-derive-enum/issues/10
//  This was written at 4:44 am and I refuse to spent any more time on fixing
//  this hack. I do not understand why the fu*ck is this feature not in diesel
//  standard library.                                       - andrew, Nov 2 2024
#[derive(Debug, Copy, Clone, Eq, PartialEq, diesel_derive_enum::DbEnum)]
#[ExistingTypePath = "crate::schema::sql_types::StatusEnum"]
pub enum UpStatus {
    Uninitialized,
    Up,
    Down,
    Paused,
}

#[derive(Debug, Clone, Queryable, Selectable, Insertable)]
#[diesel(table_name = uptime_states)]
pub struct UptimeState {
    pub id: ID,
    pub created_at: SystemTime,
    pub touched_at: SystemTime,
    pub status: UpStatus,
    pub user_id: Option<ID>,
    pub state_changed_at: SystemTime,
}

/// Result of a touch() call indicating what state transition occurred.
pub enum TouchResult {
    /// No state change (device was already Up or Paused)
    NoChange,
    /// Device connected for the first time (Uninitialized → Up)
    Connected,
    /// Device reconnected after being down (Down → Up), with time spent down
    Restored(std::time::Duration),
}

impl UptimeState {
    pub fn new(user_id: ID) -> UptimeState {
        let now = SystemTime::now();
        UptimeState {
            id: Uuid::new_v4(),
            created_at: now,
            touched_at: now,
            status: UpStatus::Uninitialized,
            user_id: Some(user_id),
            state_changed_at: now,
        }
    }

    /// Called when device pings. Returns the state transition that occurred.
    pub fn touch(&mut self) -> TouchResult {
        let now = SystemTime::now();
        self.touched_at = now;

        if self.status == UpStatus::Uninitialized {
            self.status = UpStatus::Up;
            self.state_changed_at = now;
            return TouchResult::Connected;
        }

        if self.status == UpStatus::Down {
            // Calculate how long power was off (since last state change to Down)
            let duration = now.duration_since(self.state_changed_at).unwrap_or_default();
            self.status = UpStatus::Up;
            self.state_changed_at = now;
            return TouchResult::Restored(duration);
        }
        TouchResult::NoChange
    }

    /// Called when timeout expires. Returns Some(duration) if state changed from Up to Down,
    /// where duration is the time power was on.
    pub fn go_down(&mut self) -> Option<std::time::Duration> {
        if self.status == UpStatus::Up {
            let now = SystemTime::now();
            // Calculate how long power was on (since last state change to Up)
            let duration = now.duration_since(self.state_changed_at).ok();
            self.status = UpStatus::Down;
            self.state_changed_at = now;
            return duration;
        }
        return None;
    }
}

#[derive(Debug, Clone, Serialize)]
#[serde(crate = "rocket::serde")]
pub struct UserState {
    pub user: User,
    pub ntfy: NtfyUser,
    #[serde(skip_serializing)]
    pub uptime: UptimeState,
}

pub async fn create_new_state(
    conn: &mut AsyncPgConnection,
    user_state: &UserState,
    token_id: Option<&Uuid>,
) -> Result<(), String> {
    let result = conn
        .transaction::<_, CustomError, _>(|tconn| {
            async move {
                diesel::insert_into(ntfy_users::dsl::ntfy_users)
                    .values(&user_state.ntfy)
                    .returning(ntfy_users::dsl::id)
                    .get_result::<ID>(tconn)
                    .await?;
                diesel::insert_into(users::dsl::users)
                    .values(&user_state.user)
                    .returning(users::dsl::id)
                    .get_result::<ID>(tconn)
                    .await?;
                diesel::insert_into(uptime_states::dsl::uptime_states)
                    .values(&user_state.uptime)
                    .returning(uptime_states::dsl::id)
                    .get_result::<ID>(tconn)
                    .await?;

                // Consume the invite (after user insert, since user_id has FK to users)
                if let Some(invite_id) = token_id {
                    let updated = diesel::update(invites::dsl::invites)
                        .filter(invites::dsl::id.eq(invite_id))
                        .filter(invites::dsl::is_used.eq(false))
                        .set((
                            invites::dsl::is_used.eq(true),
                            invites::dsl::user_id.eq(user_state.user.id),
                        ))
                        .execute(tconn)
                        .await?;
                    if updated == 0 {
                        return Err(CustomError::CreationFailed);
                    }
                }

                Ok(())
            }
            .scope_boxed()
        })
        .await;

    result.map_err(|err| format!("{err:?}"))
}

pub async fn get_all_states(conn: &mut AsyncPgConnection) -> R<Vec<UserState>> {
    let user_items: Vec<(User, NtfyUser)> = users::dsl::users
        .inner_join(ntfy_users::dsl::ntfy_users)
        .select((User::as_select(), NtfyUser::as_select()))
        .load::<(User, NtfyUser)>(conn)
        .await?;

    let mut all_states = Vec::new();
    for (user, ntfy) in user_items {
        let uptime = uptime_states::dsl::uptime_states
            .filter(uptime_states::dsl::user_id.eq(user.id))
            .order(uptime_states::dsl::created_at.desc())
            .select(UptimeState::as_select())
            .first::<UptimeState>(conn)
            .await?;
        all_states.push(UserState { user, ntfy, uptime });
    }

    Ok(all_states)
}

#[derive(Debug, Clone, Serialize, Queryable, Selectable, Insertable)]
#[diesel(table_name = invites)]
#[serde(crate = "rocket::serde")]
pub struct Invite {
    pub id: ID,
    pub created_at: SystemTime,
    pub token: String,
    pub is_used: bool,
    pub owner_id: Option<ID>,
    pub user_id: Option<ID>,
}

impl Invite {
    pub fn new(owner_id: ID) -> Invite {
        let rng = rand::thread_rng();
        Invite {
            id: Uuid::new_v4(),
            created_at: SystemTime::now(),
            token: rng.sample_iter(&Alphanumeric).take(24).map(char::from).collect(),
            is_used: false,
            owner_id: Some(owner_id),
            user_id: None,
        }
    }
}

pub async fn create_new_invite(conn: &mut AsyncPgConnection, invite: &Invite) -> Result<(), String> {
    let owner_id = invite.owner_id.ok_or_else(|| "Invite must have an owner".to_string())?;
    let result = conn
        .transaction::<_, CustomError, _>(|tconn| {
            async move {
                // diesel::update(invites::dsl::invites).set(invites::dsl::invites::);
                let (limit, used) = diesel::update(users::dsl::users)
                    .filter(users::dsl::id.eq(owner_id))
                    .set(users::dsl::invites_used.eq(users::dsl::invites_used + 1))
                    .returning((users::dsl::invites_limit, users::dsl::invites_used))
                    .get_result::<(i64, i64)>(tconn)
                    .await?;

                // Abort operation if limit was passed.
                if used > limit {
                    warn!("New invite failed: {used}/{limit} for uid {}!", owner_id);
                    return Err(CustomError::CreationFailed);
                }

                diesel::insert_into(invites::dsl::invites)
                    .values(invite)
                    .returning(invites::dsl::id)
                    .get_result::<ID>(tconn)
                    .await?;

                Ok(())
            }
            .scope_boxed()
        })
        .await;

    result.map_err(|err| format!("{err:?}"))
}

pub async fn get_invites_for_user(
    conn: &mut AsyncPgConnection,
    uid: ID,
) -> Result<Vec<Invite>, diesel::result::Error> {
    invites::dsl::invites
        .filter(invites::dsl::owner_id.eq(uid))
        .load::<Invite>(conn)
        .await
}

pub async fn delete_invite(
    conn: &mut AsyncPgConnection,
    invite_id: ID,
    owner_id: ID,
) -> Result<usize, diesel::result::Error> {
    conn.transaction::<_, diesel::result::Error, _>(|tconn| {
        async move {
            let invite_used = match invites::dsl::invites
                .filter(invites::dsl::id.eq(invite_id))
                .filter(invites::dsl::owner_id.eq(owner_id))
                .select(invites::dsl::is_used)
                .first::<bool>(tconn)
                .await
            {
                Ok(used) => used,
                Err(diesel::result::Error::NotFound) => return Ok(0),
                Err(e) => return Err(e),
            };

            let deleted = diesel::delete(
                invites::dsl::invites
                    .filter(invites::dsl::id.eq(invite_id))
                    .filter(invites::dsl::owner_id.eq(owner_id)),
            )
            .execute(tconn)
            .await?;

            // Reclaim invite slot if the deleted invite was unused
            if deleted > 0 && !invite_used {
                diesel::update(users::dsl::users.filter(users::dsl::id.eq(owner_id)))
                    .set(users::dsl::invites_used.eq(users::dsl::invites_used - 1))
                    .execute(tconn)
                    .await?;
            }

            Ok(deleted)
        }
        .scope_boxed()
    })
    .await
}

pub async fn delete_user(
    conn: &mut AsyncPgConnection,
    user_id: ID,
) -> Result<usize, diesel::result::Error> {
    conn.transaction::<_, diesel::result::Error, _>(|tconn| {
        async move {
            // Get ntfy_id before deleting user
            let ntfy_id: ID = users::dsl::users
                .filter(users::dsl::id.eq(user_id))
                .select(users::dsl::ntfy_id)
                .first(tconn)
                .await?;

            // Delete user (cascades uptime_states and invites via ON DELETE CASCADE)
            let deleted = diesel::delete(users::dsl::users.filter(users::dsl::id.eq(user_id)))
                .execute(tconn)
                .await?;

            // Delete ntfy user (FK points from users -> ntfy, so no cascade)
            diesel::delete(ntfy_users::dsl::ntfy_users.filter(ntfy_users::dsl::id.eq(ntfy_id)))
                .execute(tconn)
                .await?;

            Ok(deleted)
        }
        .scope_boxed()
    })
    .await
}

// User settings management

pub async fn regenerate_user_token(
    conn: &mut AsyncPgConnection,
    user_id: ID,
) -> Result<String, diesel::result::Error> {
    let rng = rand::thread_rng();
    let secret_part: String = rng.sample_iter(&Alphanumeric).take(32).map(char::from).collect();
    let new_token = format!("tk_{secret_part}");

    diesel::update(users::dsl::users.filter(users::dsl::id.eq(user_id)))
        .set(users::dsl::access_token.eq(&new_token))
        .execute(conn)
        .await?;

    Ok(new_token)
}

pub async fn update_ntfy_enabled(
    conn: &mut AsyncPgConnection,
    ntfy_id: ID,
    enabled: bool,
) -> Result<(), diesel::result::Error> {
    diesel::update(ntfy_users::dsl::ntfy_users.filter(ntfy_users::dsl::id.eq(ntfy_id)))
        .set(ntfy_users::dsl::enabled.eq(enabled))
        .execute(conn)
        .await?;
    Ok(())
}

pub async fn update_user_language(
    conn: &mut AsyncPgConnection,
    user_id: ID,
    language_code: &str,
) -> Result<(), diesel::result::Error> {
    diesel::update(users::dsl::users.filter(users::dsl::id.eq(user_id)))
        .set(users::dsl::language_code.eq(language_code))
        .execute(conn)
        .await?;
    Ok(())
}

pub async fn update_uptime_state(
    conn: &mut AsyncPgConnection,
    state: &UptimeState,
) -> Result<(), diesel::result::Error> {
    diesel::update(uptime_states::dsl::uptime_states.filter(uptime_states::dsl::id.eq(state.id)))
        .set((
            uptime_states::dsl::touched_at.eq(state.touched_at),
            uptime_states::dsl::status.eq(state.status),
            uptime_states::dsl::state_changed_at.eq(state.state_changed_at),
        ))
        .execute(conn)
        .await?;
    Ok(())
}

pub async fn get_all_unused_invites(
    conn: &mut AsyncPgConnection,
) -> Result<Vec<Invite>, diesel::result::Error> {
    invites::dsl::invites
        .filter(invites::dsl::is_used.eq(false))
        .load::<Invite>(conn)
        .await
}
